spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/toilets
    username: app
    password: app
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml

server:
  port: 8080

logging:
  level:
    root: INFO
    org.hibernate.SQL: DEBUG

app:
  s3:
    endpoint: http://localhost:9000
    bucket: toilets
    accessKey: minio
    secretKey: minio12345
    region: us-east-1
    presignTtlSeconds: 600
