spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT:5432}/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASS}
  jpa:
    hibernate:
      ddl-auto: validate
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/changelog-master.yaml

server:
  port: ${PORT:8080}
  forward-headers-strategy: framework

app:
  s3:
    endpoint: https://s3.amazonaws.com
    bucket: ${S3_BUCKET}
    accessKey: ${S3_ACCESS_KEY}
    secretKey: ${S3_SECRET_KEY}
    region: eu-central-1
    presignTtlSeconds: 600

logging:
  level:
    root: INFO
